### ISSUE TITLE
How to change speaking rate?

### ISSUE THREAD

**Issue by minderov** [tmanderson/ivona-node#12]
Ivona has a `rate` atrribute. (2.15.4 in [the documentation](http://developer.ivona.com/en/ttsresources/ssml/ssml.html)), but I could not find a way to apply it.

I tried
```javascript
ivona.createVoice(message, {
    body: {
        voice: {
            name: 'Maxim',
            language: 'ru-RU',
            gender: 'Male',
            rate: 'x-slow'
        }
     }
})
```

```javascript
ivona.createVoice(message, {
    body: {
        voice: {
            name: 'Maxim',
            language: 'ru-RU',
            gender: 'Male'
        },
        rate: 'x-slow'
     }
})
```

and the speaking rate does not change. How I am I supposed to do that?

**Comment by tmanderson** [comment]
@minderov, it looks like you're referencing the wrong documentation. IVONA Speech Cloud does allow you to send a rate along with your `createVoice` body via the `parameter` property:
```javascript
ivona.createVoice(message, {
  body: {
    voice: {
        name: 'Maxim',
        language: 'ru-RU',
        gender: 'Male',
    },
    parameters: {
        rate: 'x-slow'
    }
});
```

If you take a look at the [SpeechCloud API Documentation](http://developer.ivona.com/en/speechcloud/actions.html), there's plenty of examples in there with various types of `createVoice` requests.

I've also updated the [examples](https://github.com/tmanderson/ivona-node/blob/master/example/ssml.js) on this project with an example of how you can control the speech rate (taken from the IVONA documentation) via SSML, which allows for greater control in the generated speech patterns. Hope this helps!
