### ISSUE TITLE
Error is thrown when using proxy

### ISSUE THREAD

**Issue by stsvilik** [tmanderson/ivona-node#2]
Looks like you forgot to require("http") and attempt to use it.

**Comment by tmanderson** [comment]
I've updated the proxy code, though not using `http`. As `https` as the primary protocol for this particular module. Thanks for this.

**Comment by stsvilik** [comment]
using https on proxy that only accepts http (most common case) there will be an error thrown as well. I tried it in your code and I got error about an attempt to connect on wrong port and connection got refused. So using http in this case is preferred. Maybe you should make it configurable (i.e. https: true)
