### ISSUE TITLE
browserify-compatible package

### ISSUE THREAD

**Issue by leobel** [tmanderson/ivona-node#6]
Try to browserify the module return: Uncaught Error: Cannot find module '/node_modules/ivona-node/src/proxy'

**Comment by leobel** [comment]
I fixed the issue replacing this line: `HttpsPA = require(__dirname + '/proxy');` by this: `HttpsPA = require('./proxy');` in `src/main.js`. Since the two files are at the same deep, the module should still work properly and now `browserify` can attach the proxy functionalities located at `src/proxy.js`

**Comment by tmanderson** [comment]
Closed issue, as several other proxy-related issues have been closed.
