### ISSUE TITLE
Example usage for ListVoices wrong

### ISSUE THREAD

**Issue by yjajkiew** [tmanderson/ivona-node#8]
Hi there,

I just struggled with your example : 
`ivona.listVoices().on('end', function(voices) {
            console.log(voices);
        });`

And by looking at the source code I just realized the event emitted for getting the voices is not "end" but "complete", so the correct code to put in "example usage" would be : 
`ivona.listVoices().on('complete', function(voices) {
            console.log(voices);
        });`

**Comment by tmanderson** [comment]
@yjajkiew, sorry about that! I've gone ahead and updated the README to correctly reflect the latest streaming API and events.

Thanks for letting me know!
